name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
permissions:
  pull-requests: write
  contents: write
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Enable magic Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check flake
        uses: DeterminateSystems/flake-checker-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
