name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.10.1'
        cabal-version: '3.12.1.0'

    - name: Enable tests and benchmarks globally
      run: |
        echo "tests: True" >> cabal.project.local
        echo "benchmarks: True" >> cabal.project.local

    - name: Configure and Freeze Dependencies
      run: |
        cabal update
        cabal freeze

    - name: Cache Cabal Dependencies & Build Artifacts
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-ghc-9.10.1-cabal-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-ghc-9.10.1-cabal-

    - name: Install dependencies
      run: cabal build --only-dependencies all

    - name: Build
      run: cabal build all

    - name: Run tests
      run: cabal test all --test-show-details=direct
